name:                multikey
version:             0.1.0.0
github:              "githubuser/multikey"
license:             BSD3
author:              "Dean Bolte"
maintainer:          "dean.bolte7@gmail.com"
copyright:           "2020 Dean Bolte"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/multikey#readme>

dependencies:
- base >= 4.7 && < 5
- arithmoi
- random

library:
  source-dirs: src

executables:
  multikey-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multikey

tests:
  multikey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multikey
